const guides=[
["HEALTH","Why is my tortoise not eating?","Separate normal short-term appetite changes from temperature, reproductive, husbandry and medical causes."],
["UVB & LIGHTING","How much UVB does a tortoise need?","Use measured UVI, distance, reflector and mesh — not bulb labels alone."],
["SHELL & GROWTH","What causes pyramiding?","Understand growth rate, hydration and the limits of evidence across tortoise species."],
["HYDRATION","Why are tortoise urates white?","Know what normal urates look like, what they cannot tell you, and when changes matter."],
["PAIN & WELFARE","Can tortoises feel pain?","What reptile neurobiology and veterinary analgesia tell us about pain and humane care."],
["BEHAVIOR","Can tortoises live alone?","Distinguish social interaction from a human assumption that solitary housing means loneliness."]
];
const evidence=[["01","DIRECT SPECIES EVIDENCE","Research on the species being discussed."],["02","DIRECT TORTOISE EVIDENCE","Research on tortoises, with species limits stated."],["03","RELATED EVIDENCE","Useful chelonian or reptile evidence, never presented as species-specific proof."],["04","VETERINARY CONSENSUS","Clinical guidance supported by veterinary literature."],["05","INFERENCE / UNKNOWN","Reasoned interpretation or a genuine evidence gap, labelled clearly."]];
export default function Home(){return <main>
<header><a className="brand" href="/">TORTOISE <b>EVIDENCE</b></a><nav><a href="#answers">Guides</a><a href="#standards">Evidence</a><a href="#visuals">Visual reference</a></nav><a className="search" href="/search/">Search</a></header>
<section className="hero"><div className="heroInner"><p className="eyebrow">SCIENCE-BASED TORTOISE CARE · WITHOUT THE MYTHS</p><h1>Know what to do.<br/><em>Know why.</em></h1><p className="lead">Evidence-based answers for tortoise keepers, built from veterinary medicine, peer-reviewed research and field ecology. We show what is known, what is inferred, and what remains uncertain.</p><figure className="heroPhoto"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Testudo%20Graeca.jpg" alt="Greek tortoise (Testudo graeca)" loading="eager"/><figcaption><i>Testudo graeca</i> · real animal reference · Claro48 / Wikimedia Commons · Public domain</figcaption></figure><div className="actions"><a className="primary" href="#answers">Find an answer <span>→</span></a><a className="secondary" href="#standards">See our evidence standard</a></div><div className="trust"><span>PEER-REVIEWED SOURCES</span><span>SPECIES LIMITS STATED</span><span>NO HIDDEN UNCERTAINTY</span></div></div></section>
<section className="decisionHero"><p className="eyebrow">GET THE ANSWER FIRST</p><h2>What do you need to know?</h2><form className="decisionSearch" action="/search/" method="get"><label htmlFor="q" className="srOnly">Search tortoise care questions</label><input id="q" name="q" type="search" placeholder="Try “not eating”, “white urates”, “UVB” or “pyramiding”" autoComplete="off"/><button type="submit" aria-label="Search">→</button></form><div className="decisionPaths"><a href="/health/how-can-you-tell-if-a-tortoise-is-sick/"><strong>Something seems wrong</strong><span>Check illness signs & urgency →</span></a><a href="/health/why-is-my-tortoise-not-eating/"><strong>My tortoise is not eating</strong><span>Temperature, weight trend & red flags →</span></a><a href="/care/how-much-uvb-does-a-tortoise-need/"><strong>Check my UVB setup</strong><span>Measured UVI, shell height & shade →</span></a><a href="/care/what-temperature-does-a-tortoise-need/"><strong>Check my temperatures</strong><span>Basking zone, gradient & measurement →</span></a></div><p className="decisionPromise">Answer first. Action second. Evidence when you want to verify it.</p><p className="scopeNote"><b>Health warning:</b> severe weakness, breathing difficulty, major trauma, uncontrolled bleeding or rapid deterioration should not wait for an online guide; seek a qualified reptile veterinarian.</p></section><section id="answers" className="answers"><div className="sectionHead"><div><p className="eyebrow">START WITH A REAL QUESTION</p><h2>Answers you can use today.</h2></div><p>Read the practical answer first. Open the evidence when you want to see exactly what supports it.</p></div><div className="cards">{guides.map(([cat,title,desc])=><article key={title}><span className="category">{cat}</span><h3>{title}</h3><p>{desc}</p><a href={title==="Why is my tortoise not eating?"?"/health/why-is-my-tortoise-not-eating/":title==="How much UVB does a tortoise need?"?"/care/how-much-uvb-does-a-tortoise-need/":title==="What causes pyramiding?"?"/welfare/what-causes-pyramiding-in-tortoises/":title==="Why are tortoise urates white?"?"/health/why-are-tortoise-urates-white/":title==="Can tortoises feel pain?"?"/welfare/can-tortoises-feel-pain/":title==="Can tortoises live alone?"?"/behavior/can-tortoises-live-alone/":"#database"}>Read evidence <b>→</b></a></article>)}</div></section>
<section id="standards" className="standards"><div className="standardIntro"><p className="eyebrow">THE TORTOISE EVIDENCE STANDARD</p><h2>Repeated advice is not the same as evidence.</h2><p>Every important husbandry claim should tell you how directly it is supported. We do not silently turn research on another species into a rule for yours.</p></div><div className="evidence">{evidence.map(([n,a,b])=><div key={a}><span>{n}</span><section><strong>{a}</strong><p>{b}</p></section></div>)}</div></section>
<section id="visuals" className="visualLibrary"><div className="sectionHead"><div><p className="eyebrow">VISUAL REFERENCE</p><h2>See the animal. Understand the evidence.</h2></div><p>Good evidence is easier to use when the subject can be seen. We use real specimens and clearly label what an image can — and cannot — establish.</p></div><div className="visualGrid"><figure><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Testudo%20Graeca.jpg" alt="Greek tortoise, Testudo graeca"/><figcaption><b>SPECIES REFERENCE</b><br/><i>Testudo graeca</i> · Claro48 · Public domain</figcaption></figure><figure><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Testudo%20graeca%20top%20shell.jpg" alt="Top shell of Testudo graeca"/><figcaption><b>ANATOMY REFERENCE</b><br/>Carapace and scute pattern · Vicente.niclos · CC BY-SA 4.0</figcaption></figure><figure><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Tetudo%20graeca%20graeca%20shell%20bones.jpg" alt="Shell bones of Testudo graeca graeca"/><figcaption><b>STRUCTURAL REFERENCE</b><br/>Shell bones · Vicente.niclos · CC BY-SA 4.0</figcaption></figure></div></section><section className="principle"><p>“We explain not only <strong>how</strong> to care for a tortoise, but <strong>why</strong> the recommendation exists.”</p></section>
<footer><div><b>TORTOISE EVIDENCE</b><p>Evidence-Based Tortoise Care, Health & Welfare</p></div><small>Independent educational resource. Health concerns should be assessed by a qualified reptile veterinarian.</small></footer>
</main>}