export const metadata={title:"How Much UVB Does a Tortoise Need?",description:"A practical evidence-based guide to tortoise UVB: UVI, distance, mesh, reflector, lamp aging and species-appropriate exposure."};
const refs=[
["Baines FM et al. How much UV-B does my reptile need? The UV-Tool, a guide to the selection of UV lighting for reptiles and amphibians in captivity. J Zoo Aquarium Res. 2016;4(1):42–63.","https://jzar.org/jzar/article/view/150"],
["Ferguson GW et al. Voluntary exposure of some western-hemisphere snake and lizard species to ultraviolet-B radiation in the field: how much ultraviolet-B should a lizard or snake receive in captivity? Zoo Biol. 2010;29:317–334.","https://pubmed.ncbi.nlm.nih.gov/19358304/"],
["Selleri P, Di Girolamo N. Plasma 25-hydroxyvitamin D3 concentrations in Hermann's tortoises (Testudo hermanni) exposed to natural sunlight and two artificial ultraviolet radiation sources. Am J Vet Res. 2012;73(11):1781–1786.","https://pubmed.ncbi.nlm.nih.gov/23106459/"]
];
export default function Page(){return <main className="articlePage"><header><a className="brand" href="/">TORTOISE <b>EVIDENCE</b></a><a className="back" href="/">← All guides</a></header><article className="article"><p className="eyebrow">CARE · UVB & LIGHTING</p><h1>How much UVB does a tortoise need?</h1><p className="dek">Do not choose UVB by bulb percentage alone. What matters biologically is the ultraviolet exposure that actually reaches the tortoise at shell height, after distance, reflector, mesh and lamp aging have changed the output.</p><div className="answerBox"><b>QUICK ANSWER</b><p>Provide a usable UV gradient: a suitable higher-UV zone associated with basking and substantially lower exposure elsewhere so the tortoise can choose. Measure UVI at the animal’s level whenever possible rather than assuming a lamp label equals the dose.</p></div><div className="articleGrid"><div className="body">
<h2>Think in UVI, not “10%” or “12%”</h2><p>A lamp’s percentage is a product specification, not the ultraviolet dose received by the animal. The same lamp can produce very different UVI depending on mounting distance, reflector geometry, screen or mesh, orientation and lamp age. For enclosure design, the useful question is therefore: <b>what UVI reaches the tortoise where it can actually position its body?</b></p><div className="grade direct"><b>EVIDENCE NOTE</b><span>Direct tortoise + comparative reptile evidence</span></div>
<h2>A gradient is more useful than one enclosure-wide number</h2><p>The UV-Tool framework groups reptiles by observed basking behavior and field exposure. Mediterranean <i>Testudo</i> tortoises have commonly been treated as open/partial-sun baskers in Ferguson Zone 3. The published Zone 3 guidance gives a basking-zone target range around UVI 1.0–2.6, while recorded voluntary field exposure can extend higher. This is a husbandry framework, not proof that every individual should receive one fixed number all day.</p>
<h2>Distance can completely change the result</h2><p>UV intensity falls markedly as the animal moves farther from the source, and reflectors can concentrate output. Mesh can reduce transmission. That means copying another keeper’s lamp model without copying their fixture, distance and enclosure geometry does not reproduce their exposure.</p>
<h2>How to set it up</h2><ol><li><b>Define the basking position.</b> Measure from the UV source to the top of the shell, not to the enclosure floor.</li><li><b>Create choice.</b> Place useful UV exposure over part of the enclosure and provide shaded/lower-UV retreats.</li><li><b>Measure when possible.</b> A suitable UV Index meter lets you verify the actual result instead of estimating from packaging.</li><li><b>Recheck after changes.</b> Moving a lamp, adding mesh, changing the reflector or replacing the lamp can change exposure.</li><li><b>Use natural sunlight carefully.</b> Outdoor sunlight can provide excellent UV exposure, but heat, predators, escape, toxic plants and access to shade must be controlled.</li></ol>
<div className="warning"><b>IMPORTANT DISTINCTION</b><p>UV vision and UVB physiology are not the same question. UVB is used in vitamin D biology; whether a tortoise can visually perceive particular ultraviolet wavelengths does not determine its UVB requirement.</p></div>
<h2>What the evidence does not justify</h2><p>There is no defensible universal rule that every tortoise should use the same lamp percentage, the same mounting distance or one exact UVI regardless of species and enclosure. Nor should a keeper assume that “more UVB” is automatically better. Good design provides appropriate exposure plus behavioral choice.</p>
<h2 id="references">Primary references</h2><div className="references">{refs.map(([t,u],i)=><p key={u}><span>{i+1}.</span><a href={u} target="_blank" rel="noreferrer">{t}</a></p>)}</div></div>
<aside><b>AT A GLANCE</b><dl><dt>Measure</dt><dd>UVI at shell height</dd><dt>Do not rely on</dt><dd>Bulb percentage alone</dd><dt>Design goal</dt><dd>UV gradient + shade + behavioral choice</dd><dt>Common framework</dt><dd>Mediterranean Testudo: Ferguson Zone 3</dd><dt>Zone 3 guide range</dt><dd>UVI 1.0–2.6 at the basking zone</dd></dl><a href="#references">Primary sources ↓</a></aside></div></article></main>}