export const metadata={title:"Why Is My Tortoise Not Eating?",description:"A practical, evidence-graded guide to loss of appetite in tortoises: temperature, season, reproduction, husbandry and medical red flags."};
const refs=[
["Frankenberger J, Kölle P. Assessment of the nutritional condition in Mediterranean tortoises (Testudo spp.) — an overview. Tierärztl Prax. 2024.","https://pubmed.ncbi.nlm.nih.gov/39637919/"],
["Brooks MA. Important Factors in Chelonian Nutrition. Vet Clin North Am Exot Anim Pract. 2024;27(1):85–100.","https://pubmed.ncbi.nlm.nih.gov/37661549/"],
["Moller C, Heatley JJ. Diagnostic Clinical Pathology of Tortoises. Vet Clin North Am Exot Anim Pract. 2022;25(3):755–783.","https://pubmed.ncbi.nlm.nih.gov/36122950/"],
["Merck Veterinary Manual. Clinical Procedures for Reptiles — Greek tortoise renal disease example.","https://www.merckvetmanual.com/exotic-and-laboratory-animals/reptiles/clinical-procedures-for-reptiles"]
];
export default function Page(){return <main className="articlePage"><header><a className="brand" href="/">TORTOISE <b>EVIDENCE</b></a><a className="back" href="/">← All guides</a></header><article className="article"><p className="eyebrow">HEALTH · APPETITE</p><h1>Why is my tortoise not eating?</h1><p className="dek">Loss of appetite is a sign, not a diagnosis. First check whether the tortoise can reach an appropriate body temperature and whether a normal seasonal or reproductive change is plausible — but persistent anorexia, lethargy or other abnormalities deserve veterinary assessment.</p><div className="answerBox"><b>QUICK ANSWER</b><p>A tortoise may stop eating because it is too cool to function normally, because activity is changing with season or reproduction, because husbandry is limiting normal behavior, or because it is ill. Do not try to diagnose the cause from appetite alone.</p></div><div className="articleGrid"><div className="body">
<h2>Start with the environment</h2><p>Tortoises are ectotherms. Their physiology depends on access to suitable environmental temperatures, so an animal that cannot warm appropriately may also eat less. Check the temperatures where the tortoise actually sits, not only the thermostat setting. Lighting, access to a usable basking area, hydration and recent husbandry changes should be reviewed at the same time.</p><div className="grade direct"><b>EVIDENCE NOTE</b><span>Physiology + veterinary evidence</span></div>
<h2>Context matters</h2><p>Season, sex, reproductive status, diet and whether an animal is captive or wild can materially affect clinical interpretation in tortoises. A single missed meal therefore has less diagnostic value than the pattern: duration, body-weight trend, activity, feces and urates, breathing, eyes and nose, oral appearance and any recent environmental change.</p>
<h2>When “wait and see” is the wrong approach</h2><p>Reduced appetite becomes more concerning when it persists or occurs with lethargy, weight loss, dehydration, abnormal breathing or discharge, oral lesions, swelling, abnormal urination/defecation, inability to bask normally, or a marked change from that individual’s baseline. Published tortoise cases show that anorexia can accompany serious renal, infectious, cardiac and neoplastic disease; appetite alone cannot distinguish them.</p><div className="warning"><b>Seek a reptile-experienced veterinarian promptly</b><p>if your tortoise is deteriorating, has respiratory difficulty, marked weakness, neurologic signs, significant trauma, repeated vomiting/regurgitation, or persistent anorexia with other abnormalities.</p></div>
<h2>What to do today</h2><ol><li><b>Measure, don’t guess.</b> Verify the thermal gradient and basking conditions at tortoise level.</li><li><b>Review the pattern.</b> Note when eating changed, activity, body weight, feces/urates and any other signs.</li><li><b>Remove obvious husbandry barriers.</b> Ensure easy access to appropriate heat, light, water, shelter and familiar suitable food.</li><li><b>Do not force-feed blindly.</b> Treating “not eating” without finding the cause can delay diagnosis.</li><li><b>Escalate when the pattern is abnormal.</b> A reptile veterinarian can combine examination, weight/body condition and, where indicated, imaging or laboratory testing.</li></ol>
<h2>What the evidence does not support</h2><p>There is no scientifically defensible universal rule such as “a tortoise can safely go X days without food.” Species, age, season, body condition, temperature, hydration, reproductive state and disease all change the risk. A long fasting tolerance in one context is not permission to ignore new anorexia in another.</p>
<h2>References</h2><div className="references">{refs.map(([t,u],i)=><p key={u}><span>{i+1}.</span><a href={u} target="_blank" rel="noreferrer">{t}</a></p>)}</div></div>
<aside><b>AT A GLANCE</b><dl><dt>Symptom</dt><dd>Reduced or absent food intake</dd><dt>First check</dt><dd>Measured environment + whole-animal behavior</dd><dt>Evidence strength</dt><dd>Veterinary evidence; cause is context-dependent</dd><dt>Do not assume</dt><dd>“Picky,” “hibernating,” or calcium deficient from appetite alone</dd></dl><a href="#references">Primary sources ↓</a></aside></div></article></main>}